# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.13 on 2018-09-28 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
>>>>>>> issue76_django1.8


class Migration(migrations.Migration):

<<<<<<< HEAD
    initial = True

=======
>>>>>>> issue76_django1.8
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=32)),
                ('revoked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_user', to=settings.AUTH_USER_MODEL)),
=======
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('token', models.CharField(max_length=32, editable=False)),
                ('revoked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(related_name='api_user', to=settings.AUTH_USER_MODEL)),
>>>>>>> issue76_django1.8
            ],
            options={
                'verbose_name': 'API Token',
            },
        ),
    ]
