# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-28 14:27
from __future__ import unicode_literals

import core.encryption.encryptionFields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name=b'Path to record collection')),
                ('record_id', models.CharField(max_length=50, verbose_name=b'Record ID in External System')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalRecordGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('external_records', models.ManyToManyField(to='core.ExternalRecord')),
            ],
            options={
                'ordering': ['group'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalRecordLabel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100, verbose_name=b'Label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalRecordRelation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_record', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_record', to='core.ExternalRecord')),
                ('related_record', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_record', to='core.ExternalRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name=b'External System Name')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name=b'External System URL')),
                ('description', models.TextField(help_text=b'Please briefly describe this external system.', verbose_name=b'System Description')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('name', core.encryption.encryptionFields.EncryptCharField(max_length=255, unique=True, verbose_name=b'Group Name')),
                ('client_key', models.CharField(max_length=255, verbose_name=b'Client KEY')),
                ('is_locking', models.BooleanField(default=False, verbose_name=b'Lock Group')),
                ('description', models.TextField(help_text=b'Please briefly describe this Group.', verbose_name=b'Group Description')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupEhbKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('key', core.encryption.encryptionFields.EncryptCharField(blank=True, editable=False, max_length=255, unique=True, verbose_name=b'EHB KEY')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name=b'Remote Host IP Address')),
                ('host_name', models.CharField(blank=True, default=b'', max_length=255, verbose_name=b'Name')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subject_id_label', models.CharField(default=b'Record ID', max_length=50, verbose_name=b'Unique Subject Record ID Label')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PedigreeSubjectRelation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protocol_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[(b'generic', b'Generic'), (b'label', b'Label'), (b'file', b'File'), (b'familial-parent', b'Familial-Parent'), (b'familial-child', b'Familial-Child'), (b'familial-sibling', b'Familial-Sibling'), (b'familial-half-sibling', b'Familial-half-Sibling'), (b'diagnosis', b'Diagnosis')], default=b'Label', max_length=255, verbose_name=b'Relation Type')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Descriptor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('first_name', core.encryption.encryptionFields.EncryptCharField(max_length=255, verbose_name=b'First Name')),
                ('last_name', core.encryption.encryptionFields.EncryptCharField(max_length=255, verbose_name=b'Last Name')),
                ('organization_subject_id', core.encryption.encryptionFields.EncryptCharField(max_length=255, verbose_name=b'Organization Subject Record ID')),
                ('dob', core.encryption.encryptionFields.EncryptDateField(help_text=b'Please use date format: <em>YYYY-MM-DD</em>', max_length=10, verbose_name=b'Date Of Birth')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
            options={
                'ordering': ['organization', 'organization_subject_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Please use date format: <em>YYYY-MM-DD</em>', verbose_name=b'Record Last Modified DateTime')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
                ('subjects', models.ManyToManyField(to='core.Subject')),
            ],
            options={
                'ordering': ['group'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectValidation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regex', models.CharField(max_length=70)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='pedigreesubjectrelation',
            name='subject_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_1', to='core.Subject'),
        ),
        migrations.AddField(
            model_name='pedigreesubjectrelation',
            name='subject_1_role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_1_role', to='core.Relation'),
        ),
        migrations.AddField(
            model_name='pedigreesubjectrelation',
            name='subject_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_2', to='core.Subject'),
        ),
        migrations.AddField(
            model_name='pedigreesubjectrelation',
            name='subject_2_role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_2_role', to='core.Relation'),
        ),
        migrations.AlterUniqueTogether(
            name='machineclient',
            unique_together=set([('ip_address', 'host_name')]),
        ),
        migrations.AddField(
            model_name='group',
            name='ehb_key',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.GroupEhbKey', unique=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='subjects',
            field=models.ManyToManyField(blank=True, through='core.ExternalRecord', to='core.Subject'),
        ),
        migrations.AddField(
            model_name='externalrecordrelation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Relation'),
        ),
        migrations.AddField(
            model_name='externalrecordgroup',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
        migrations.AddField(
            model_name='externalrecord',
            name='external_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ExternalSystem', verbose_name=b'External System'),
        ),
        migrations.AddField(
            model_name='externalrecord',
            name='label',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ExternalRecordLabel', verbose_name=b'Label'),
        ),
        migrations.AddField(
            model_name='externalrecord',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subject'),
        ),
    ]
