# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-27 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedigreeSubjectRelation',
            new_name='SubjectFamRelation',
        ),
        migrations.AlterField(
            model_name='relation',
            name='typ',
            field=models.CharField(choices=[(b'generic', b'Generic'), (b'label', b'Label'), (b'file', b'File'), (b'familial-parent', b'Familial-Parent'), (b'familial-child', b'Familial-Child'), (b'familial-sibling', b'Familial-Sibling'), (b'familial-half-sibling', b'Familial-Half-Sibling'), (b'familial-grandparent', b'Familial-Grandparent'), (b'familial-grandchild', b'Familial-Grandchild'), (b'familial-cousin', b'Familial-Cousin'), (b'familial-nephew-niece', b'Familial-Nephew-Niece'), (b'familial-aunt-uncle', b'Familial-Aunt-Uncle'), (b'familial-great-aunt-uncle', b'Familial-Great-Aunt-Uncle'), (b'familial-grand-nephew-niece', b'Familial-grand-nephew-niece'), (b'familial', b'Familial'), (b'diagnosis', b'Diagnosis')], default=b'Label', max_length=255, verbose_name=b'Relation Type'),
        ),
    ]
