# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-26 13:36
from __future__ import unicode_literals

import core.encryption.encryptionFields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='externalrecord',
            name='external_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ExternalSystem', verbose_name='External System'),
        ),
        migrations.AlterField(
            model_name='externalrecord',
            name='label',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ExternalRecordLabel', verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='externalrecord',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='externalrecord',
            name='path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Path to record collection'),
        ),
        migrations.AlterField(
            model_name='externalrecord',
            name='record_id',
            field=models.CharField(max_length=50, verbose_name='Record ID in External System'),
        ),
        migrations.AlterField(
            model_name='externalrecordgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='externalrecordgroup',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='externalrecordlabel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='externalrecordlabel',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='externalrecordlabel',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='externalrecordrelation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='externalrecordrelation',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='externalrecordrelation',
            name='relation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Relation'),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='description',
            field=models.TextField(help_text='Please briefly describe this external system.', verbose_name='System Description'),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='External System Name'),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='url',
            field=models.URLField(max_length=255, unique=True, verbose_name='External System URL'),
        ),
        migrations.AlterField(
            model_name='group',
            name='client_key',
            field=models.CharField(max_length=255, verbose_name='Client KEY'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Please briefly describe this Group.', verbose_name='Group Description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_locking',
            field=models.BooleanField(default=False, verbose_name='Lock Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=core.encryption.encryptionFields.EncryptCharField(max_length=255, unique=True, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='groupehbkey',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='groupehbkey',
            name='key',
            field=core.encryption.encryptionFields.EncryptCharField(blank=True, editable=False, max_length=255, unique=True, verbose_name='EHB KEY'),
        ),
        migrations.AlterField(
            model_name='groupehbkey',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='machineclient',
            name='host_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='machineclient',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='Remote Host IP Address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject_id_label',
            field=models.CharField(default='Record ID', max_length=50, verbose_name='Unique Subject Record ID Label'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descriptor'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='typ',
            field=models.CharField(choices=[('generic', 'Generic'), ('label', 'Label'), ('file', 'File'), ('familial-parent', 'Familial-Parent'), ('familial-child', 'Familial-Child'), ('familial-sibling', 'Familial-Sibling'), ('familial-half-sibling', 'Familial-Half-Sibling'), ('familial-grandparent', 'Familial-Grandparent'), ('familial-grandchild', 'Familial-Grandchild'), ('familial-cousin', 'Familial-Cousin'), ('familial-nephew-niece', 'Familial-Nephew-Niece'), ('familial-aunt-uncle', 'Familial-Aunt-Uncle'), ('familial-great-aunt-uncle', 'Familial-Great-Aunt-Uncle'), ('familial-grand-nephew-niece', 'Familial-grand-nephew-niece'), ('familial', 'Familial'), ('diagnosis', 'Diagnosis')], default='Label', max_length=255, verbose_name='Relation Type'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dob',
            field=core.encryption.encryptionFields.EncryptDateField(help_text='Please use date format: <em>YYYY-MM-DD</em>', max_length=10, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='first_name',
            field=core.encryption.encryptionFields.EncryptCharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='last_name',
            field=core.encryption.encryptionFields.EncryptCharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='organization_subject_id',
            field=core.encryption.encryptionFields.EncryptCharField(max_length=255, verbose_name='Organization Subject Record ID'),
        ),
        migrations.AlterField(
            model_name='subjectfamrelation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='subjectfamrelation',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='subjectgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime'),
        ),
        migrations.AlterField(
            model_name='subjectgroup',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime'),
        ),
    ]
