# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-30 15:56
from __future__ import unicode_literals

import core.encryption.encryptionFields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190726_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAudit',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Creation DateTime')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Please use date format: <em>YYYY-MM-DD</em>', verbose_name='Record Last Modified DateTime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='User Name')),
                ('change_type', models.CharField(max_length=50, verbose_name='Change type')),
                ('change_type_ehb_pk', models.CharField(blank=True, max_length=20, verbose_name='Change Type eHB PK')),
                ('change_action', models.CharField(blank=True, max_length=50, verbose_name='Change action')),
                ('change_field', models.CharField(blank=True, max_length=50, verbose_name='Change field')),
                ('old_value', core.encryption.encryptionFields.EncryptCharField(blank=True, max_length=255, verbose_name='Old Value')),
                ('new_value', core.encryption.encryptionFields.EncryptCharField(blank=True, max_length=255, verbose_name='New value')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subject', verbose_name='Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
